build:
  image: python:2
  commands:
    - echo "Building data service."
  run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py


publish:
  docker:
    repo: $$DOCKER_USERNAME/tac-bot
    tag: latest
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL


deploy:
  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/$$DEPLOYMENT_DIR/$$BOT_NAME/$$DOCKER_USERNAME/restart?force=true
    when:
      branch: "master"

  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/$$DEPLOYMENT_DIR/$$BOT_NAME-dev/$$DOCKER_USERNAME/restart?force=true
    when:
      branch: "dev"


notify:
  spark:
    image: hpreston/drone-spark
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
